name: Build release binaries

# Allow the workflow to create/read/update releases and upload assets
permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.x'

      - name: Build binary
        run: |
          OS=${{ matrix.os }}
          ARCH=${{ matrix.arch }}
          fname="tcp_ping_prometheus-${OS}-${ARCH}"
          if [ "$OS" = "windows" ]; then fname="${fname}.exe"; fi
          mkdir -p dist
          echo "Building ${fname}"
          CGO_ENABLED=0 GOOS=$OS GOARCH=$ARCH go build -ldflags="-s -w" -o "dist/${fname}" ./...

      - name: Package binary
        run: |
          OS=${{ matrix.os }}
          ARCH=${{ matrix.arch }}
          base="tcp_ping_prometheus-${OS}-${ARCH}"
          bin="dist/${base}"
          if [ "$OS" = "windows" ]; then
            bin="${bin}.exe"
            zip -j "dist/${base}.zip" "$bin"
            echo "PKG=dist/${base}.zip" >> $GITHUB_ENV
          else
            tar -C dist -czf "dist/${base}.tar.gz" "${base}"
            echo "PKG=dist/${base}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PKG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}